import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <React.Fragment>
      <Navbar />
      <body className={inter.className}>{children}</body>
    </React.Fragment>
  );
}
